FROM wordpress:cli
COPY bin/setup-wp.sh /setup-wp.sh
USER root
RUN apk update && apk add jq \
    && adduser -D -u 1000 xfs  # Create xfs user
RUN apk update && apk add jq
RUN chmod +x /setup-wp.sh
ENTRYPOINT ["/setup-wp.sh"]
USER xfs
