<?php
/**
 * Main request class
 *
 * @package WC_Klarna_Payments/Classes/Requests
 */

defined( 'ABSPATH' ) || exit;

use Krokedil\Klarna\Utilities\ApiCredentialsUtility;
use KrokedilKlarnaPaymentsDeps\Krokedil\WpApi\Request;
use KrokedilKlarnaPaymentsDeps\Krokedil\WpApi\Logger;

/**
 * Base class for all request classes.
 */
abstract class KP_Requests extends Request {
	/**
	 * The Klarna merchant Id, or MID. Used for calculating the request auth.
	 *
	 * @var string
	 */
	protected $merchant_id;

	/**
	 * The Klarna shared api secret. Used for calculating the request auth.
	 *
	 * @var string
	 */
	protected $shared_secret;

	/**
	 * Iframe options generated by helper class used to modify what the Klarna Payments iframe looks like.
	 *
	 * @var KP_IFrame
	 */
	protected $iframe_options;

	/**
	 * Filter to use for the request args.
	 *
	 * @var string
	 */
	protected $request_filter = 'wc_klarna_payments_request_args';

	/**
	 * The credentials resolved for this request, or null if the request class supplies its own.
	 *
	 * @var array|null
	 */
	protected $credentials = null;

	/**
	 * The error from resolving the credentials, if there was one.
	 *
	 * @var WP_Error|null
	 */
	protected $credentials_error = null;

	/**
	 * Class constructor.
	 *
	 * @param mixed $arguments The request arguments.
	 */
	public function __construct( $arguments ) {
		$settings = get_option( 'woocommerce_klarna_payments_settings', array() );

		// Resolve the credentials first, since the credential set decides the API region in the base URL.
		$resolved = $this->resolve_credentials( $arguments );

		if ( is_wp_error( $resolved ) ) {
			$this->credentials_error = $resolved;
		} elseif ( is_array( $resolved ) ) {
			$this->credentials = $resolved;
		}

		$region_country = $this->credentials['country_code'] ?? ( $arguments['country'] ?? '' );

		$config = array(
			'slug'                   => 'klarna_payments',
			'plugin_version'         => WC_KLARNA_PAYMENTS_VERSION,
			'plugin_short_name'      => 'KP',
			'plugin_user_agent_name' => 'KP',
			'logging_enabled'        => 'no' !== ( $settings['logging'] ?? 'no' ),
			'extended_debugging'     => 'extra' === ( isset( $settings['logging'] ) ? $settings['logging'] : 'no' ),
			'base_url'               => $this->get_base_url( $region_country, $settings ),
		);

		parent::__construct( $config, $settings, $arguments );
		$this->set_credentials();
		$this->iframe_options = new KP_IFrame( $settings );

		add_filter( 'wc_kp_image_url_cart_item', array( $this, 'maybe_allow_product_urls' ), 1, 1 );
		add_filter( 'wc_kp_url_cart_item', array( $this, 'maybe_allow_product_urls' ), 1, 1 );
		add_filter( 'wc_kp_image_url_order_item', array( $this, 'maybe_allow_product_urls' ), 1, 1 );
		add_filter( 'wc_kp_url_order_item', array( $this, 'maybe_allow_product_urls' ), 1, 1 );
	}

	/**
	 * Returns headers for Klarna API requests.
	 *
	 * @return array
	 */
	protected function get_request_headers() {
		$session_reference = '';

		if ( ! empty( $this->arguments['session_id'] ) ) {
			$session_reference = $this->arguments['session_id'];
		} elseif ( method_exists( KP_WC()->session, 'get_klarna_session_id' ) ) {
			$session_reference = KP_WC()->session->get_klarna_session_id();
		}

		$integration_data = array(
			'name'              => 'WOOCOMMERCE',
			'module_name'       => 'Klarna for WooCommerce',
			'module_version'    => WC_KLARNA_PAYMENTS_VERSION,
			'session_reference' => $session_reference,
		);

		return array(
			'Authorization'                 => $this->calculate_auth(),
			'Content-Type'                  => 'application/json',
			'X-Klarna-Integration-Metadata' => wp_json_encode(
				array(
					'integrator'  => $integration_data,
					'originators' => array( $integration_data ),
				)
			),
		);
	}

	/**
	 * Sets the environment.
	 *
	 * @param string $country The country code.
	 * @param array  $settings The settings array.
	 */
	protected function get_base_url( $country, $settings ) {
		$testmode = wc_string_to_bool( $settings['testmode'] ?? 'no' ); // Get the testmode setting.

		$region = strtolower(
			/**
			 * Filters the Klarna API region used to build the API base URL.
			 *
			 * @link https://docs.krokedil.com/klarna-for-woocommerce/customization/hooks-action-filter/#change-the-base-region-for-api-requests
			 * @param string $region The Klarna API region, derived from the country endpoint. Blank for EU.
			 */
			apply_filters( 'klarna_base_region', ApiCredentialsUtility::get_region( $country ) )
		); // Get the region from the country parameters, blank for EU.
		$playground = $testmode ? '.playground' : ''; // If testmode is enabled, add playground to the subdomain.
		$subdomain  = "api{$region}{$playground}"; // Combine the string to one subdomain.

		return "https://{$subdomain}.klarna.com/"; // Return the full base url for the api.
	}

	/**
	 * Resolve which Klarna credentials to use for this request.
	 *
	 * Request classes that supply their own credentials override this and return null.
	 *
	 * @param array $arguments The request arguments.
	 *
	 * @return array|WP_Error|null The credentials, an error, or null to keep the ones the request class sets.
	 */
	protected function resolve_credentials( $arguments ) {
		// Requests about an existing Klarna order pass the credential set the purchase was made with.
		if ( ! empty( $arguments['credentials_country'] ) ) {
			return ApiCredentialsUtility::get_credentials( $arguments['credentials_country'] );
		}

		$country = $arguments['country'] ?? kp_get_klarna_country();

		return ApiCredentialsUtility::resolve_for_request( $country, $this->get_purchase_currency( $arguments ) );
	}

	/**
	 * Get the currency this request is for.
	 *
	 * Has to match the purchase_currency in the payload, since the credentials depend on the currency.
	 *
	 * @param array $arguments The request arguments.
	 *
	 * @return string The currency code.
	 */
	protected function get_purchase_currency( $arguments ) {
		if ( ! empty( $arguments['currency'] ) ) {
			return $arguments['currency'];
		}

		if ( ! empty( $arguments['order_id'] ) ) {
			$order = wc_get_order( $arguments['order_id'] );

			if ( $order ) {
				return $order->get_currency();
			}
		}

		return get_woocommerce_currency();
	}

	/**
	 * Sets Klarna credentials.
	 */
	public function set_credentials() {
		$this->merchant_id   = $this->credentials['merchant_id'] ?? '';
		$this->shared_secret = $this->credentials['shared_secret'] ?? '';
	}

	/**
	 * Make the request, or return the credentials error if we could not resolve any.
	 *
	 * @return array|WP_Error
	 */
	public function request() {
		if ( is_wp_error( $this->credentials_error ) ) {
			KP_WC()->logger()->error( 'Could not resolve the Klarna API credentials for the request: ' . $this->credentials_error->get_error_message() );

			return $this->credentials_error;
		}

		return parent::request();
	}

	/**
	 * Calculates the auth header for the request.
	 *
	 * @return string
	 */
	public function calculate_auth() {
		return 'Basic ' . base64_encode( $this->merchant_id . ':' . htmlspecialchars_decode( (string) $this->shared_secret, ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML401 ) ); // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions -- Base64 used to calculate auth headers.
	}

	/**
	 * Maybe filters out product urls before we send them to Klarna based on settings.
	 *
	 * @param string $url The URL to the product or product image.
	 * @return string|null
	 */
	public function maybe_allow_product_urls( $url ) {
		if ( 'yes' === $this->settings['send_product_urls'] ?? false ) {
			$url = null;
		}
		return $url;
	}

	/**
	 * Gets the error message from the Klarna payments response.
	 *
	 * @param array $response The response from the request.
	 * @return WP_Error
	 */
	public function get_error_message( $response ) {
		$error_message    = '';
		$decoded_response = json_decode( $response['body'], true );
		// Get the error messages.
		if ( null !== $decoded_response && isset( $decoded_response['error_messages'] ) ) {
			foreach ( $decoded_response['error_messages'] as $error ) {
				$error_message = "$error_message $error";
			}
		}
		$code          = wp_remote_retrieve_response_code( $response );
		$error_message = empty( $error_message ) ? $response['response']['message'] : $error_message;
		return new WP_Error( $code, $error_message );
	}

	/**
	 * Get the user agent string, passing the full request URL as the 2nd parameter to the
	 * http_headers_useragent filter so other plugins can modify it based on the URL.
	 *
	 * @return string
	 */
	protected function get_user_agent() {
		$wp_version             = get_bloginfo( 'version' );
		$wp_url                 = get_bloginfo( 'url' );
		$wc_version             = WC()->version;
		$plugin_user_agent_name = $this->config['plugin_user_agent_name'];
		$plugin_version         = $this->config['plugin_version'];
		$php_version            = phpversion();
		return apply_filters(
			'http_headers_useragent',
			"WordPress/{$wp_version}; {$wp_url} - WooCommerce: {$wc_version} - {$plugin_user_agent_name}: {$plugin_version} - PHP Version: {$php_version} - Krokedil",
			$this->get_request_url()
		);
	}

	/**
	 * Logs the response from the request.
	 *
	 * @param array|\WP_Error $response The response from the request.
	 * @param array           $request_args The request args.
	 * @param string          $request_url The request URL.
	 *
	 * @return void
	 */
	protected function log_response( $response, $request_args, $request_url ) {
		$code = wp_remote_retrieve_response_code( $response );

		// Get the response body if its not a WP_Error.
		$response_body = is_wp_error( $response ) ? array() : json_decode( wp_remote_retrieve_body( $response ), true );

		// Parse the Request body into an array if its json format.
		$request_body         = $request_args['body'] ?? '';
		$decoded_body         = json_decode( $request_body );
		$request_args['body'] = $decoded_body ?? $request_args['body'] ?? null;
		$request_args         = $this->sanitize_request_args( $request_args );

		$arguments = $this->arguments;
		if ( isset( $arguments['username'] ) ) {
			$arguments['username'] = KP_Logger::REDACTED;
		}
		if ( isset( $arguments['password'] ) ) {
			$arguments['password'] = KP_Logger::REDACTED;
		}

		KP_WC()->logger()->info(
			wp_json_encode(
				KP_Logger::redact(
					array(
						'type'        => $this->method,
						'title'       => $this->log_title,
						'arguments'   => $arguments,
						'request'     => $request_args,
						'request_url' => $request_url,
						'response'    => array(
						'body' => $response_body,
						'code' => $code,
						),
						'timestamp'   => date( 'Y-m-d H:i:s' ),    // phpcs:ignore WordPress.DateTime.RestrictedFunctions -- Date is not used for display.
					'stack'           => Logger::get_stack( $this->config['extended_debugging'] ),
					'plugin_version'  => $this->config['plugin_version'],
					)
				)
			)
		);
	}
}
